name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - uses: numtide/clean-git-action@v1
      - run: yarn install --immutable
      - run: yarn configure
      - run: yarn build
      - run: yarn lint
