on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: "yarn"
      - uses: numtide/clean-git-action@main
      - run: yarn version check
        if: github.event_name == 'pull_request'
      - run: yarn constraints
      - run: yarn install --immutable
      - run: yarn configure
      - run: yarn build
      - run: yarn lint
